// <auto-generated />
using System;
using HookVault.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HookVault.Migrations
{
    [DbContext(typeof(HookVaultDbContext))]
    [Migration("00000000000003_LastReplayEditedBody")]
    partial class LastReplayEditedBody
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("HookVault.Domain.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("BodyHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForwardStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ForwardedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastReplayAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LastReplayWithEditedBody")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureHeader")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SignatureValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationDetails")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash");

                    b.HasIndex("Provider");

                    b.HasIndex("ProviderEventId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Status");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
